# Generated by Django 3.2.4 on 2023-11-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_respuesta', models.IntegerField(db_column='idRespuesta', primary_key=True, serialize=False)),
                ('gama', models.CharField(db_column='gama', max_length=15)),
                ('frecuencia', models.CharField(db_column='frecuencia', max_length=30)),
                ('met_pago', models.CharField(db_column='met_pago', max_length=30)),
                ('dispositivo', models.CharField(db_column='dispositivo', max_length=30)),
                ('opc_correo', models.CharField(db_column='opc_correo', max_length=10)),
                ('serv_mensajeria', models.CharField(db_column='serv_mensajeria', max_length=30)),
                ('opc_chatbot', models.CharField(db_column='opc_chatbor', max_length=10)),
                ('opc_atencion_pers', models.CharField(db_column='opc_atencion_pers', max_length=10)),
                ('tiempo_nave', models.CharField(db_column='tiempo_nav', max_length=50)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='RegistroU',
            fields=[
                ('id_registroU', models.IntegerField(db_column='idGenero', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellidop', models.CharField(db_column='apellidoP', max_length=100)),
                ('apellidom', models.CharField(db_column='apellidoM', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=50)),
                ('contra', models.CharField(db_column='contra', max_length=100)),
            ],
            options={
                'db_table': 'R_usuario',
            },
        ),
    ]
