# Generated by Django 4.2.7 on 2024-01-14 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
            ],
            options={
                'db_table': 'categoria_producto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellidop', models.CharField(db_column='apellidoP', max_length=100)),
                ('apellidom', models.CharField(db_column='apellidoM', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=150)),
                ('contra', models.CharField(db_column='contra', max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id_respuesta', models.AutoField(db_column='id_respuesta', primary_key=True, serialize=False)),
                ('gama', models.CharField(db_column='gama', max_length=35)),
                ('frecuencia', models.CharField(db_column='frecuencia', max_length=100)),
                ('met_pago', models.CharField(db_column='met_pago', max_length=100)),
                ('dispositivo', models.CharField(db_column='dispositivo', max_length=100)),
                ('opc_correo', models.CharField(db_column='opc_correo', max_length=10)),
                ('serv_mensajeria', models.CharField(db_column='serv_mensajeria', max_length=30)),
                ('opc_chatbot', models.CharField(db_column='opc_chatbor', max_length=10)),
                ('opc_atencion_pers', models.CharField(db_column='opc_atencion_pers', max_length=10)),
                ('tiempo_nave', models.CharField(db_column='tiempo_nav', max_length=100)),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
            ],
            options={
                'db_table': 'marca_producto',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=500)),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(db_column='imagen', upload_to='static/imagenes_productos/')),
                ('categoria', models.CharField(db_column='categoria', max_length=100)),
                ('marca', models.CharField(db_column='marca', max_length=100)),
                ('unidadMedida', models.CharField(db_column='unidadmedida', max_length=100)),
                ('tamaño', models.CharField(db_column='tamaño', max_length=100)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='RegistroU',
            fields=[
                ('id_registroU', models.AutoField(db_column='id_registro', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('apellidop', models.CharField(db_column='apellidoP', max_length=100)),
                ('apellidom', models.CharField(db_column='apellidoM', max_length=100)),
                ('email', models.CharField(db_column='email', max_length=150)),
                ('contra', models.CharField(db_column='contra', max_length=100)),
                ('numero_telefono', models.CharField(blank=True, db_column='numero_telefono', max_length=12, null=True)),
            ],
            options={
                'db_table': 'R_usuario',
            },
        ),
        migrations.CreateModel(
            name='Tamaño',
            fields=[
                ('id_tomaño', models.AutoField(db_column='id_tamaño', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
            ],
            options={
                'db_table': 'tamaño',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id_unidadMedida', models.AutoField(db_column='id_unidadMedida', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
            ],
            options={
                'db_table': 'unidad_medida',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('id_productofk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.producto')),
                ('id_registroUfk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.registrou')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
