# Generated by Django 4.2.7 on 2024-01-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id_venta', models.AutoField(db_column='id_venta', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'prueba',
            },
        ),
    ]
