# Generated by Django 3.2.4 on 2023-11-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrou',
            name='id_registroU',
            field=models.IntegerField(db_column='id_registro', primary_key=True, serialize=False),
        ),
    ]
