# Generated by Django 3.2.4 on 2023-11-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231109_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=35)),
                ('price', models.CharField(db_column='price', max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
